import MainLayout from '../layouts/mainLayout';
import SectionLayout from '../layouts/sectionLayout';
import {Helmet} from "react-helmet";

function TermsOfUsePage() {
  return (
    <MainLayout style={{ fontSize: '15px' }}>
    <Helmet>
      <link rel="canonical" href="https://www.firelabinc.com/terms-of-use" />
    </Helmet>
      {/* Title */}
      <SectionLayout>
        <h1 className='display-4 fw-bold'>TERMS OF USE <span className='highlight'>AGREEMENT</span></h1>
      </SectionLayout>

      <SectionLayout className='text-start'>
        {/* Welcome to the website of FireLab LLC */}
        <p>Welcome to the website of FireLab LLC (collectively “FireLab ” “website” “site” “we” “our” or “us”). FireLab is the owner of a certain proprietary web based software application named “Aries” which facilitates the inspection, testing and maintenance of fire life safety systems.</p>
        <p>(the “<b>Services</b>”).</p>
        <p>The following Terms of Use, together with any documents they expressly incorporate by reference (collectively, these “Terms of Use”), govern your (“Your” “You” or “User”) access to and use of this website (the “Website”) and use of the Services. </p>
        <p>Please read the Terms of Use carefully before you start to use the Website or Services. <b>By using the Website or Services, you accept and agree to be bound and abide by these Terms of Use and our Privacy Policy incorporated herein by reference (“Privacy Policy“)</b> available at www.firelabinc.com. If you do not want to agree to these Terms of Use or the Privacy Policy, you must not access or use the Website or Services. </p>
        <p>This Website and Services are offered and available to users who are 18 years old or older. By using this Website or Services you represent and warrant that you are of legal age to form a binding contract with FireLab. If you are not 18 years old or older, you must not access or use the Website or Services.</p>
        <p><b>ARBITRATION NOTICE AND CLASS ACTION WAIVER: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS.</b></p>
        <p>Be advised that FireLab, including its employees are not offering or providing any financial or legal advice on its website or through its Services.</p>
        <br></br>
        
        {/* CERTAIN USE LIMITATIONS */}
        <p><b>CERTAIN USE LIMITATIONS</b></p>
        <p>The website is offered to you free of charge to view, while other Services, including using our SaaS application through our Services are fee based and you are required to execute Our Subscription Agreement as a condition to being granted access to Our Services.</p>
        <p>FireLab grants you a non-exclusive, non-transferable, limited permission to access and display the Web pages within this site as a user, customer or potential customer of the Services provided you comply with these Terms of Use, and all copyright, trademark, and other proprietary notices remain intact. You may only use a crawler to crawl this Web site as permitted by this Web site’s robots.txt protocol, and FireLab may block any crawlers in its sole discretion. The use authorized under this agreement is non-commercial in nature (e.g., you may not sell the content you access on or through this Web site.) All other use of this site is prohibited. All rights not expressly granted herein are reserved.</p>
        <p>You may not copy, modify, distribute, sell, or lease any part of our Website or Services, nor may you reverse engineer or attempt to extract the source code of that software, unless applicable laws prohibit these restrictions or you have our written permission to do so. </p>
        <p>Except for the limited permission in the preceding paragraphs, FireLab does not grant you any express or implied rights or licenses under any patents, trademarks, copyrights, or other proprietary or intellectual property rights. You may not mirror any of the content from this site on another Website or in any other media. Any software and other materials that are made available for downloading, access, or other use from this site with their own license terms will be governed by such terms, conditions, and notices. Your failure to comply with such terms or any of the terms on this site will result in automatic termination of any rights granted to you, without prior notice, and you must immediately destroy all copies of downloaded materials in your possession, custody or control. </p>
        <p>You agree that at any time in our sole discretion, without notice to you and without liability of any kind, we may make improvements and/or changes to this Website, restrict or terminate your access to or use of any part or all of the Website, or refuse, move, or remove any material that you submitted to the Website.</p>
        <p>You represent, warrant, and agree that any information or materials you submit to or post on the Website (a) shall be true, accurate, and current; (b) will not, directly or indirectly, violate, infringe or breach any duty toward or rights of any person or entity, including without limitation any copyright, trademark, service mark, trade secret, other intellectual property, publicity or privacy, or Fair Housing right; (c) will not be fraudulent, misleading, hateful, tortious, defamatory, slanderous, libelous, abusive, violent, threatening, profane, vulgar or obscene; (c) will not harass others, promote bigotry, racism, hatred or harm against any individual or group, promote discrimination based on race, sex, religion, nationality, sexual orientation or age, or otherwise interfere with another's use of the Website; (d) will not promote illegal or harmful activities; and (e) will not be illegal, unlawful or contrary to any applicable laws or regulations where created, displayed, or accessed.</p>
        <p>You agree not to (and not to assist any third party to):</p>
        <p>(a) engage in commercial use of the Website or any content on the Website;</p>
        <p>(b) reproduce, copy, display, store, perform, re-post, publish, transmit, distribute, sell, offer for sale, license, modify, create derivative works, or otherwise use any portion of the content offered on the Website for other than your own personal, non-commercial use;</p>
        <p>(c) remove any copyright, trademark or other proprietary rights notices contained in or on the Website or any content or other material obtained via the Website or any services on the Website;</p>
        <p>(d) use any robot, spider, site search/retrieval application, or other automated device, process or means to access, retrieve or index any portion of the Website, such as for purposes of constructing or populating a searchable database of business or property reviews;</p>
        <p>(e) collect or harvest any information about other users for any purpose;</p>
        <p>(f) reformat or frame any portion of the web pages that are part of the Website;</p>
        <p>(g) create user accounts by automated means or under false, misleading or fraudulent pretenses;</p>
        <p>(h) create or transmit unwanted electronic communications such as “spam” to other users or otherwise interfere with other users’ enjoyment of the Website;</p>
        <p>(i) transmit any viruses, worms, defects, Trojan horses or other items of a destructive nature;</p>
        <p>(j) use the Website to violate the security of any computer network, crack passwords or security encryption codes, or transfer or store illegal material, including any material that may be deemed threatening or obscene;</p>
        <p>(k) copy or modify the HTML code used to generate web pages on the Website;</p>
        <p>(l) use any device, software or procedure that interferes with the proper working of the Website, or otherwise attempt to interfere with the proper working of the Website;</p>
        <p>(m) take any action that imposes an unreasonable or disproportionately large load on our IT infrastructure;</p>
        <p>(n) modify, adapt, translate, or reverse engineer any portion of the Website;</p>
        <p>(o) use the Website to violate any law or regulation, including but not limited to Fair Housing laws and regulations, or</p>
        <p>(p) use the Website for any purpose that is unlawful or prohibited or unauthorized by these Terms of Use.</p>
        <br></br>
        
        {/* PAYMENT */}
        <p><b>PAYMENT.</b></p>
        <p>For Services offered on a payment or subscription basis, the following terms apply, unless FireLab or its third party affiliates notify you otherwise in writing. If you are given access to the FireLab web based SaaS application “Aries” through Our Services you are required to sign Our Subscription Agreement. This Agreement also incorporates by reference and includes program ordering and payment terms provided to you on the website for the Services:</p>
        <ol style={{paddingLeft: '1em'}}>
          <li>Payments will be billed to you in U.S. dollars, and your account will be debited when you subscribe and provide your payment information, unless stated otherwise in the program ordering or payment terms on the website for the Services.</li>
          <li>FireLab utilizes the services of a third party payments processor to process all credit card payments you make for Services offered by FireLab.</li>
          <li>
            You must pay with one of the following:
            <ol style={{paddingLeft: '1em'}}>
              <li>A valid credit card acceptable to FireLab;</li>
              <li>A valid debit card acceptable to FireLab;</li>
              <li>Sufficient funds in a checking or savings account to cover an electronic debit of the payment due;<br></br>or</li>
              <li>By another payment option FireLab provides to you in writing.</li>
            </ol>
          </li>
          <li>If your payment and registration information is not accurate, current, and complete and you do not notify us promptly when such information changes, we may suspend or terminate your account and refuse any use of the Services.</li>
          <li>If you do not notify us of updates to your payment method (e.g., credit card expiration date), to avoid interruption of your service, we may participate in programs supported by your card provider (e.g., updater services, recurring billing programs, etc.) to try to update your payment information, and you authorize us to continue billing your account with the updated information that we obtain.</li>
          <li>FireLab will automatically renew your monthly, quarterly, or annual Services at the then-current rates, unless the Services are cancelled or terminated under this Agreement.</li>
          <li>Additional cancellation or renewal terms may be provided to you on the website for the Services.</li>
        </ol>
        <br></br>
        
        {/* USE WITH YOUR MOBILE DEVICE */}
        <p><b>USE WITH YOUR MOBILE DEVICE</b></p>
        <p>
          Use of the Website and Services may be available through a compatible mobile device, Internet access and may require software. You agree that you are solely responsible for these requirements, including any applicable changes, updates and fees as well as the terms of your agreement with your mobile device and telecommunications provider.
          <br></br>
          FIRELAB MAKES NO WARRANTIES OR REPRESENTATIONS OF ANY KIND, EXPRESS, STATUTORY OR IMPLIED AS TO:
        </p>
        <ol style={{paddingLeft: '1em'}}>
          <li>THE AVAILABILITY OF TELECOMMUNICATION SERVICES FROM YOUR PROVIDER AND ACCESS TO THE SERVICES AT ANY TIME OR FROM ANY LOCATION;</li>
          <li>ANY LOSS, DAMAGE, OR OTHER SECURITY INTRUSION OF THE TELECOMMUNICATION SERVICES; AND</li>
          <li>ANY DISCLOSURE OF INFORMATION TO THIRD PARTIES OR FAILURE TO TRANSMIT ANY DATA, COMMUNICATIONS OR SETTINGS CONNECTED WITH THE SERVICES.</li>
        </ol>
        <br></br>
        
        {/* THIRD PARTY INFORMATION, MATERIALS, PRODUCTS, AND SERVICES */}
        <p><b>THIRD PARTY INFORMATION, MATERIALS, PRODUCTS, AND SERVICES</b></p>
        <p>This Website may feature information, materials, products, and services provided by third parties, which may include content providers, payment processors, advertisers, and other users (collectively, the “Third Party Information”). All such information, materials, products, and services made available by a third party are those of the third party and not us. We make no representation or warranty with respect to, nor do we guarantee or endorse, and we disclaim any express or implied warranty relating to, the accuracy, completeness, quality, timeliness, non-infringing nature, legality, condition, or reliability of any third party information, materials, products, or services.</p>
        <p>You agree that we have no responsibility or duty to review, pre-screen, or approve, and that we shall not be responsible or liable for, any third party information, materials, products, or services or any loss or damage of any kind suffered by you or any third party arising out of or relating to any of them.</p>
        <p>If you choose to communicate or contract with any third party, or use any information, materials, services or products of any third party, you agree that you will address any issues or disputes regarding such matters directly with the third party, and not us. You acknowledge that your participation in any services provided by a third party or purchase of any product from a third party will constitute your consent to such third party's terms of service or terms of use with respect to such service or product.</p>
        <br></br>

        {/* LINKS TO THIRD PARTY SITES */}
        <p><b>LINKS TO THIRD PARTY SITES</b></p>
        <p>This Website may contain links, inline frames, feeds, embedded content to or from websites (collectively, “Third Party Links” or "Links") operated by parties other than FireLab. Such links are provided for your convenience only, and do not indicate any endorsement of the material on such websites or any association with their operators. You agree that FireLab is not responsible or liable for such websites, the availability or contents of such websites, any products or services they offer, or any damages any of the foregoing may cause you.</p>
        <p>IN NO EVENT SHALL FIRELAB BE LIABLE FOR ANY DAMAGES SUFFERED BY A WEBSITE USER (WHETHER CONSEQUENTIAL, DIRECT, INCIDENTAL, EXEMPLARY, INDIRECT, PUNITIVE, SPECIAL OR OTHERWISE) ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, ANY LINKED SITE OR THIRD PARTY WEBSITE OR RELATED SERVICES, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, STRICT LIABILITY, TORT OR OTHER THEORIES OF LIABILITY, AND ALSO REGARDLESS OF WHETHER FIRELAB WAS GIVEN ACTUAL OR CONSTRUCTIVE NOTICE THAT SUCH DAMAGES WERE POSSIBLE.</p>
        <p>The Website utilizes Google Maps, Google Translate and related content licensed to us by Google and its licensors. By using the Google Maps and Google Translate features available on the Website, you are agreeing to be bound by the applicable policies, Terms of Use of Google.</p>
        <br></br>

        {/* Linking to this site */}
        <p><b>Linking to this site</b></p>
        <p>FireLab consents only to links to this website in which the link and the pages that are activated by the link do not: (a) create frames around any page on this Web site or use other techniques that alter in any way the visual presentation or appearance of any content within this site; (b) misrepresent your relationship with FireLab; (c) imply that FireLab approves or endorses you, your Web site, or your service or product offerings; and (d) present false or misleading impressions about FireLab or otherwise damage the goodwill associated with FireLab’s name or trademarks. As a further condition to being permitted to link to this site, you agree that FireLab may at any time, in its sole discretion, terminate permission to link to this Web site. In such event, you agree to immediately remove all links to this Web site and to cease any related use of FireLab’s trademarks.</p>
        <br></br>

        {/* The Content of Others */}
        <p><b>The Content of Others</b></p>
        <p>Content (“content”) on our website may be produced by other users and other third parties (“third party content”) and may contain content or materials (“materials”) from publishers or other Users. Whether that content is posted publicly or sent privately, the content is the sole responsibility of the person or organization that submitted it. Although FireLab reserves the right to review all content that appears on the website or Services and to remove any content that violates these Terms, we do not necessarily review all of it. So we cannot—and do not—take responsibility for any content that others provide through the website or Services.</p>
        <p>Any opinions, advice, statements, services, offers, or other information or content expressed or made available by Users and third parties, including information providers or any other users of the Website or Services, are those of the respective author(s) or distributor(s) and not of FireLab.</p>
        <p>You are responsible for your use of the website and Services and for any Content you provide, including compliance with applicable laws, rules, and regulations. As such, you should only provide Content that you are comfortable sharing with others. </p>
        <p>Any use or reliance on any Content or materials posted via the website or Services or obtained by you through the website or Services is at your own risk. We do not endorse, support, represent or guarantee the completeness, truthfulness, accuracy, or reliability of any Content or communications posted via the website or Services or endorse any opinions expressed via the website or Services. You understand that by using the website or Services, you may be exposed to Content that might be offensive, harmful, inaccurate or otherwise inappropriate, or in some cases, postings that have been mislabeled or are otherwise deceptive. All Content is the sole responsibility of the person who originated such Content. We may not monitor or control the Content posted via the website or Services and, we cannot take responsibility for such Content.</p>
        <br></br>
        <p>We will respond to notices of alleged copyright infringement that comply with applicable law and are properly provided to us.</p>
        <p>Through these Terms, we make clear that we do not want the website or Services put to bad uses. But because we do not review all content, we cannot guarantee that content on the website or Services will always conform to our Terms.</p>
        <p>You may be able to post User Content. You must not post any User Content that is threatening, abusive, unlawful, misleading, fraudulent, discriminatory, libelous, defamatory, obscene or otherwise objectionable, or that contains ethnic, sexual, racial or other discriminating slurs. You must also not post any User Content that contains proprietary information, trade secrets, confidential information, solicitations, advertisements, chain letters, pyramid schemes, investment opportunities, or other unsolicited commercial communication (except as otherwise expressly permitted by us in writing), or encourages or causes spamming or flooding.</p>
        <p>You are prohibited from posting any User Content containing state, government or federal identification information or numbers (whether your own or of another person), such as national identification number, social security number, passport number, insurance number, driver’s license number, immigration number, or any other similar number, code, or identifier. Posting such identification information could possibly cause identity theft. FireLab may remove any such identification information, but we are under no obligation to do so and have no responsibility and disclaim all liability or damages for any user posting of such identification information.</p>
        <p>FireLab reserves the right to disclose all User Content and other relevant or related information, and the circumstances surrounding their transmission, to any third party in connection with operating the Site and Services; to protect itself, its affiliates, its partners and its users or visitors; and to comply with legal obligations or governmental requests. What this means is that we may honor law enforcement or court-mandated requests such as subpoenas or search warrants to reveal a user’s electronic address and identity, or other properly requested information.</p>
        <p>Although we have no obligation to do so, we may monitor User Content, and reserve the right to delete any User Content or portion thereof that, in FireLab’s sole discretion, violates the above rules, including any User Content that is unrelated to the specific area of the Site or Services on which it is posted, or that is an advertisement, or other commercial message, or that FireLab determines in its sole discretion to be inappropriate. If you believe that any User Content violates this Agreement or our policies, we encourage you to report the content or conduct to us so that we may have the opportunity to consider whether to remove the content or not. Just so there is no ambiguity in these Terms of Use, FireLab does not have any obligation to remove any User Content, and whether User Content is deemed to be inappropriate or violates any FireLab policy will always remain within the sole discretion of FireLab.</p>
        <p>Please take note of the following: Section 230 of the U.S. Communications Decency Act provides that:</p>
        <p>(1) Treatment of publisher or speaker</p>
        <p>No provider or user of an interactive computer service shall be treated as the publisher or speaker of any information provided by another information content provider.</p>
        <p>(2) Civil liability No provider or user of an interactive computer service shall be held liable on account of-</p>
        <p>(A) any action voluntarily taken in good faith to restrict access to or availability of material that the provider or user considers to be obscene, lewd, lascivious, filthy, excessively violent, harassing, or otherwise objectionable, whether or not such material is constitutionally protected; or</p>
        <p>(B) any action taken to enable or make available to information content providers or others the technical means to restrict access to material described in paragraph (1).</p>
        <br></br>

        {/* License to User Content and Feedback */}
        <p><b>License to User Content and Feedback</b></p>
        <p>You retain your rights to any Content you submit, post or display on or through the website. What’s yours is yours — you own your Content (and your photos and videos are part of the Content).</p>
        <p>By submitting, posting or displaying Content on or through the website, you grant us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such Content in any and all media or distribution methods (now known or later developed). This license authorizes us to make your Content available to the rest of the world and to let others do the same. You agree that this license includes the right for FireLab to provide, promote, and improve the website or Services and to make Content submitted to or through the website or Services available to other companies, organizations or individuals for the syndication, broadcast, distribution, promotion or publication of such Content on other media and services, subject to our Terms of Use for such Content use. Such additional uses by FireLab, or other companies, organizations or individuals, may be made with no compensation paid to you with respect to the Content that you submit, post, transmit or otherwise make available through the website.</p>
        <p>You represent and warrant that you have all the rights, power and authority necessary to grant the rights granted herein to any Content that you submit.</p>
        <p>Only to the extent as permitted by law, if you post content or submit material to FireLab, including photographs or material you grant Us a nonexclusive, worldwide, perpetual, (revocable only as described below), fully paid, royalty-free, sublicensable right and license to use, sell, make, sublicense, reproduce, distribute, perform, display, prepare derivative works from and otherwise exploit all such content and materials for the purpose of publishing material on the Services, FireLab’s website or its publisher partners, maintaining FireLab website and promoting FireLab without restriction. You further grant to FireLab, its affiliates, and sublicensees the right to use your user name, user name, and/or trademarks and logos in connection with any such User Content or FireLab marketing materials or content that we might publish or display on the site or Services.</p>
        <p>As a user of the site or Services, you represent, warrant and acknowledge that: (i) you own the User Content that you submit, display, post or otherwise make available on or through the Site, or that you otherwise have the right to grant the license set forth in this section, (ii) that all such User Content, and its submission, display, posting or availability on or through the Site does not violate any applicable law or the privacy rights, publicity rights, copyrights, contract rights, intellectual property rights or any other rights of any person or entity, and (iii) such submission, posting, display or availability on or through the Site does not result in or cause any breach of contract between you and any third party. You further agree to pay for all royalties, fees, damages, and any other monies of any kind owed to any person or entity by reason of such User Content. You agree to defend, indemnify and hold harmless FireLab and its affiliates and sublicensees from all claims of any kind resulting from any such User Content. If you desire to request to revoke the license granted by you in this Section for any such User Content, you must email Us at: hello@firelabinc.com with a copy of your passport or national identity card (for identity verification purposes) and request removal of such User Content. Your certified letter of request to remove such User Content must include (a) your name, address, telephone number, and email address; (b) the signature of the applicable rights holder for such User Content or a person authorized to act on behalf of the rights holder; (c) identification of the User Content for which the license is to be revoked, and please provide all necessary information reasonably sufficient to allow FireLab to locate and remove such User Content on the Site; (d) a written statement certifying that you have a good faith belief that you are the rights holder or authorized by the rights holder to revoke the license for the designated User Content; and (e) a statement that the information in the request to remove the user content is accurate, and under penalty of perjury, that you are the rights holder or are authorized to act on behalf of the rights holder with respect to such User Content that you desire to be removed from the site.</p>
        <p>Only if you desire to do so voluntarily, you may offer feedback to FireLab about the functionality and performance of the Site, including, without limitation, identifying ways to modify the site, potential errors, making improvements, fixing bugs, or enhancements (“Feedback”). By providing Feedback, you hereby grant to FireLab a nonexclusive, worldwide, perpetual, irrevocable, royalty-free, sublicensable right and license to use, sell, make sublicense, reproduce, perform, distribute, display, prepare derivative works from and otherwise exploit all such Feedback for any purpose without restriction. You agree that FireLab may disclose any or all Feedback to any third party in any manner, and you agree that FireLab may sublicense any or all Feedback in any form to any third party without restriction. By providing any Feedback, you agree that your provision of such Feedback is unsolicited, gratuitous and without restriction, and will not put FireLab under any confidentiality, fiduciary, or other any obligation, and that FireLab is free to use such Feedback without any additional compensation to you, and that we are free to disclose such Feedback on a non-confidential basis or otherwise to anyone. You further acknowledge that, by accepting any Feedback, we do not waive any rights to use similar or related ideas previously known to FireLab, or developed or created by its employees, or derived from sources other than you.</p>
        <br></br>

        {/* Confidential information */}
        <p><b>Confidential information</b></p>
        <p>FireLab does not want to receive confidential or proprietary information from you through our website. Please note that any information or material sent to FireLab will be deemed NOT to be confidential. By sending FireLab any information or material, you grant FireLab an unrestricted, irrevocable license to copy, reproduce, publish, upload, post, transmit, distribute, publicly display, perform, modify, create derivative works from, and otherwise freely use, those materials or information. You also agree that FireLab is free to use any ideas, concepts, know-how, or techniques that you send us for any purpose. However, we will not release your name or otherwise publicize the fact that you submitted materials or other information to us unless: (a) we obtain your permission to use your name; or (b) we first notify you that the materials or other information you submit to a particular part of this site will be published or otherwise used with your name on it; or (c) we are required to do so by law. Personally-identifiable information that you submit to FireLab for the purpose of receiving products or services will be handled in accordance with our privacy policies. </p>
        <br></br>

        {/* Global availability */}
        <p><b>Global availability</b></p>
        <p>Information FireLab publishes on the Internet may contain references or cross references to FireLab’s products, programs and services that are not announced or available in your country. Such references do not imply that FireLab intends to announce or make available such products, programs, or services in your country.</p>
        <br></br>

        {/* PRIVACY */}
        <p><b>PRIVACY</b></p>
        <p>You agree that we may collect, use, and share information about you in any manner permitted by the Privacy Policy posted on this Website.</p>
        <br></br>

        {/* YOUR ACCOUNT */}
        <p><b>YOUR ACCOUNT</b></p>
        <p>You agree that you are responsible for maintaining the confidentiality of your account and password, for restricting access to your computer, and for all activities that occur under your password or your account. You agree: (a) that you will not disclose your Site password to anyone, (b) that you will not allow others to utilize your account, (c) to ensure that you fully exit from your account at the end of each session, (d) to immediately change your password if you become aware that your account has been compromised, (e) to immediately notify us of any unauthorized use of your password or account, or any other breach of security, and (f) that you will be solely responsible for safeguarding your password and for any actions taken under your password or account, whether authorized by you or not.</p>

        {/* Respecting Copyright */}
        <p><b>Respecting Copyright</b></p>
        <p>We honor the requirements set forth in the Digital Millennium Copyright Act. We therefore take reasonable steps to expeditiously remove from our Website or Services any infringing material that we become aware of. And if FireLab becomes aware that one of its users has repeatedly infringed copyrights, we will take reasonable steps within our power to terminate the user's account.</p>
        <p>We make it easy for you to report suspected copyright infringement. If you believe that anything on the the website infringes a copyright that you own or control, please contact Us:</p>
        <br></br>

        {/* FireLab */}
        <p><b>FireLab</b></p>
        <p>Attn: Administrator</p>
        <p>Email: hello@firelabinc.com</p>
        <p>If you file a notice by mail with Us, it must comply with the requirements set forth at 17 U.S.C. § 512(c)(3). That means the notice must:</p>
        <ul>
          <li>contain the physical or electronic signature of a person authorized to act on behalf of the copyright owner;</li>
          <li>identify the copyrighted work claimed to have been infringed;</li>
          <li>identify the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed, or access to which is to be disabled, and information reasonably sufficient to let us locate the material;</li>
          <li>provide your contact information, including your address, telephone number, and an email address;</li>
          <li>provide a personal statement that you have a good-faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
          <li>provide a statement that the information in the notification is accurate and, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</li>
        </ul>
        <br></br>

        {/* SOFTWARE AVAILABLE ON THIS WEBSITE */}
        <p><b>SOFTWARE AVAILABLE ON THIS WEBSITE</b></p>
        <p>Any software that is made available to download from this Website or the Services ("Software") is the copyrighted work of FireLab and/or its suppliers. Your use of any Software is governed by the terms of the end user license agreement (EULA), if any, that accompanies or is included with the Software. You may not install or use any Software that is accompanied by or includes a license agreement unless you first agree to the license agreement terms.</p>
        <p>All Software, including without limitation all code and active controls contained in this Website and the Services is owned by FireLab and/or its suppliers and is protected by copyright laws and international treaty provisions. Any unlicensed reproduction or redistribution of any Software is expressly prohibited by law, and may result in severe civil and criminal penalties. Without limiting the foregoing, copying or reproduction of any Software to any other server or location for further reproduction or redistribution is expressly prohibited.</p>
        <br></br>

        {/* Intellectual property rights */}
        <p><b>Intellectual property rights</b></p>
        <p>You acknowledge that all intellectual property rights in the website and Services, and the Documents anywhere in the world belong to FireLab or our licensors, that rights in them are licensed (not sold) to you, and that you have no rights in, or to, the Services or the Documents other than the right to use each of them in accordance with these Terms.</p>
        <p>You acknowledge that you have no right to have access to the website or Services in source-code form.</p>
        <br></br>

        {/* Trademark Information */}
        <p><b>Trademark Information</b></p>
        <p>You agree that all of FireLab’s trademarks, trade names, service marks, and other logos and brand features that are displayed via the website and Services (collectively, the “Marks”) are trademarks and the property of FireLab. You agree not to display or use Our Marks in any manner without Our prior permission. Sponsor and third party website trademarks are the property of the respective Sponsors and third parties. The display of any Sponsor or third parties trademarks via the website and Services does not necessarily mean that FireLab has an affiliation with these entities.</p>
        <br></br>

        {/* Disclaimers */}
        <p><b>Disclaimers</b></p>
        <p>We try to keep the website and Services up and running and free of annoyances. But we make no promises that we will succeed.</p>
        <p>THE WEBSITE AND SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" AND TO THE EXTENT PERMITTED BY APPLICABLE LAW WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. IN ADDITION, WHILE FIRELAB ATTEMPTS TO PROVIDE A GOOD USER EXPERIENCE, WE DO NOT REPRESENT OR WARRANT THAT: (A) THE WEBSITE AND SERVICES WILL ALWAYS BE SECURE, ERROR-FREE, OR TIMELY; (B) THE WEBSITE AND SERVICES WILL ALWAYS FUNCTION WITHOUT DELAYS, DISRUPTIONS, OR IMPERFECTIONS; OR (C) THAT ANY FIRELAB CONTENT, USER CONTENT, THIRD PARTY CONTENT, MATERIALS OR INFORMATION YOU OBTAIN ON OR THROUGH THE WEBSITE OR SERVICES WILL BE TIMELY OR ACCURATE.</p>
        <p>FIRELAB TAKES NO RESPONSIBILITY AND ASSUMES NO LIABILITY FOR ANY CONTENT OR MATERIALS OF ANY KIND THAT YOU, ANOTHER USER, OR A THIRD PARTY CREATES, UPLOADS, POSTS, SENDS, RECEIVES, OR STORES ON OR THROUGH OUR WEBSITE AND SERVICES. YOU UNDERSTAND AND AGREE THAT YOU MAY BE EXPOSED TO CONTENT THAT MIGHT BE OFFENSIVE, ILLEGAL, MISLEADING, OR OTHERWISE INAPPROPRIATE, NONE OF WHICH FIRELAB WILL BE RESPONSIBLE FOR.</p>
        <p>FIRELAB DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, SECURITY, ACCURACY, OR USEFULNESS WITH RESPECT TO FIRELAB'S SERVICES, CONTENT, THE WEBSITE, OR INFORMATION CONTAINED ON THE WEBSITE OR SERVICES INCLUDING ANY THIRD PARTY SITES OR THIRD PARTY LINKS.</p>
        <br></br>
        <p>TO THE EXTENT PERMITTED BY LAW THE EXCLUSION OR LIMITATION OF CERTAIN WARRANTIES, OR SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU. </p>
        <br></br>

        {/* Limitation of Liability */}
        <p><b>Limitation of Liability</b></p>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAWS, YOU AGREE THAT FIRELAB, ITS AFFILIATES, AGENTS AND THEIR RESPECTIVE OFFICERS, DIRECTORS, OWNERS AND EMPLOYEES WILL NOT BE LIABLE FOR ANY PERSONAL INJURY, EMOTIONAL DISTRESS, DEATH OR FOR ANY INDIRECT, DIRECT, CONSEQUENTIAL, PUNITIVE OR SPECIAL DAMAGES OF ANY KIND, INCLUDING LOST PROFITS, LOSS OF BUSINESS OR OTHERWISE, ARISING OUT OF OR RELATING IN ANY WAY TO THIS AGREEMENT, YOUR USE OF THE WEBSITE OR YOUR USE OF FIRELAB’S SERVICES WHETHER SUCH CLAIM IS BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), INDEMNITY, OR OTHERWISE, EVEN IF FIRELAB OR ITS AFFILIATES, OR THEIR THIRD-PARTY LICENSORS, HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY REMEDY. SUCH LIMITATION OF LIABILITY SHALL APPLY WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF OR RELIANCE ON THE WEBSITE OR SERVICES, OR FROM RELIANCE OR DAMAGE CAUSED BY: (I) ANY INFORMATION, MATERIALS, FIRELAB CONTENT, USER CONTENT OR THIRD PARTY CONTENT POSTED ON THE WEBSITE OR SERVICES, (II) FROM THE INABILITY TO USE THE WEBSITE OR SERVICES, OR FROM THE INTERRUPTION, SUSPENSION, OR TERMINATION OF THE WEBSITE OR SERVICES (INCLUDING SUCH DAMAGES INCURRED BY THIRD PARTIES). THIS LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES RECEIVED THROUGH ANY THIRD PARTY OR LINKED SITES MADE AVAILABLE ON THE WEBSITE OR SERVICES FROM THIRD PARTY WEBSITES. THIS LIMITATION SHALL ALSO APPLY, WITHOUT LIMITATION, TO LOST PROFITS, OR LOST DATA. SUCH LIMITATION SHALL FURTHER APPLY WITH RESPECT TO THE PERFORMANCE OR NON-PERFORMANCE OF THE WEBSITE OR SERVICES OR ANY INFORMATION THAT APPEARS ON, OR IS LINKED OR RELATED IN ANY WAY TO, THE WEBSITE OR SERVICES. SUCH LIMITATION SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY, AND TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
        <p>YOU ALSO AGREE THAT FIRELAB HAS NO LIABILITY AND OFFERS NO GUARANTEES RELATING TO ANY OF THE RESULTS THAT MAY BE OBTAINED BY YOUR USE OF THE SERVICES OR FROM ANY THIRD PARTY COMPANY RECOMMENDATIONS OR PRODUCTS, OR FOR THE DESCRIPTIONS OF THIRD PARTY COMPANY OFFERINGS, PRODUCTS, GOODS OR SERVICES, ADVICE OR RECOMMENDATIONS. YOU ALSO AGREE THAT YOUR USE OF ANY PRODUCTS AND SERVICES OFFERED BY ANY THIRD PARTIES ON OUR WEBSITE OR SERVICES ARE USED AT YOUR SOLE RISK. YOU ALSO AGREE THAT ANY RECOMMENDATIONS THAT YOU RECEIVE ON THE WEBSITE OR SERVICES MADE BY ANY THIRD PARTY COMPANIES THAT YOU ACT UPON ARE DONE AT YOUR SOLE RISK AND WE HAVE NO LIABILITY WHATSOEVER WITH REGARD TO ANY THIRD PARTY COMPANY RECOMMENDATIONS.</p>
        <p>TO THE EXTENT PERMITTED BY LAW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, OR SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
        <p>User acknowledges and agrees that without the foregoing exclusions and limitations of liability, FireLab would not be able to offer the website or services, and that such exclusions and limitations of liability shall apply, even if they would cause user’s remedies under this agreement to fail of their essential purpose.</p>
        <br></br>

        {/* INDEMNIFICATION */}
        <p><b>INDEMNIFICATION</b></p>
        <p>To the fullest extent permitted by law, you agree to indemnify and hold FireLab and its owners, members, managers, officers, employees, and affiliates harmless from and against all claims, demands, suits, damages, losses, liabilities, and expenses, including reasonable attorney’s fees, arising out of or relating to (a) your breach of any of these Terms of Use or other terms of use contained on this Website; (b) your negligence, misconduct, or other wrongful act or omission; (c) your use or misuse of this Website or any of the Third Party Information, links, materials, products, or services available on or through this Website including any content you posted on the site; (d) any action of any person with whom you shared your password, account, computer, or other device; (e) any information or material you submitted to or posted on the Website; or (f) any violation or infringement of any intellectual property, privacy, publicity, confidentiality, Fair Housing, or proprietary rights of any third-party, or any violation of any law or regulation, arising from your use of the Website.</p>
        <br></br>

        {/* MODIFICATION OF TERMS OF USE */}
        <p><b>MODIFICATION OF TERMS OF USE</b></p>
        <p>FireLab reserves the right to change these Terms of Use, and any other terms of use on the Website, at any time in its sole discretion, without prior notice and without liability to you of any kind, by posting the modified Terms of Use or other terms of use on this Website. By using the Website after our posting of any changes to these Terms of Use or other terms of use (other than simply to read the modified terms and delete your account), you agree to the changes and the modified terms. All changes shall be effective immediately upon posting, shall apply prospectively only, and no change shall apply to any dispute, controversy or claim pending or in progress at, or arising before or out of events occurring before, the time of the change, or alter any provisions with respect to a matter occurring prior to the time of the change.</p>
        <p><b>CONSENT TO USE OF DATA. You agree that FireLab may collect and use technical data and related information—including but not limited to technical information about your device, system and Services software, and peripherals—that is gathered periodically to facilitate the provision of software updates, product support, and other services to you (if any) related to the paid use of our Subscription Services.</b></p>
        <p>Data also may include your name, email addresses, telephone numbers and any information you provide logging in to the Services or any information pertaining to your personally identifiable information (PII) including financial information.. Data may also include information about your customers including names, addresses. You have designed, created and provided all of your data without the participation or involvement of FireLab. You are responsible for any actions you take with respect to the Data, including uploading it to the Services or using the Services to share or otherwise make available such Data to third parties. You are responsible for ensuring that you have all the rights and permissions needed to use the Data in connection with the Services. You Shall have the sole responsibility for the accuracy, quality, integrity, legality, reliability, appropriateness of and copyright permissions for all Data entered into the Services. FireLab assumes no responsibility for the accuracy, propriety, or usefulness to You of the Data. FireLab shall not be liable to You or any third-parties for any loss, damage or expense whatsoever and howsoever arising from any Data entered into the Services by You or by an entity on your behalf unless such data is protected under federal or state law. You acknowledge that FireLab will rely on the accuracy of the Data provided to FireLab by You as it performs its requested functions under this Agreement. You acknowledge that you own all of the Data or have all rights to grant such licenses to FireLab to use such Information in furtherance of providing the Services without infringement or violation of any third party rights. FireLab provides no warranties, representations or indemnification to You for Your access to, and use of the Data.</p>
        <p>You grant a revocable license and consent to FireLab’s use of any data that you provide or that we may collect about you through the Website and Services, in compliance with Our Privacy Policy. You give consent to FireLab to use the Data when integrating with third party company systems to perform services on FireLab’s behalf relating to the functionality of the Services and that You consent to FireLab using Data that may include protected health information and personally identifiable information containing social security numbers and credit card information. We will only use such data with our partners or service providers who perform functions to enable FireLab to provide its Services.</p>
        <p>You acknowledge and agree that FireLab shall have the right to use any data collected or created by You in your use of the Services related to selling, publishing, disclosing or sharing combined data and information from many Users with our partners in order to help our partners market and sell our Products pursuant to written agreements with confidentiality, privacy and security obligations. All such information includes data derived from personal information in aggregated, anonymous form and does not identify You individually.</p>
        <br></br>

        {/* Governing Law/Arbitration. */}
        <p>By using FireLab’s Website or Services, you agree that the laws of the State of Delaware without regard to principles of conflict of laws, will govern this Agreement and any dispute of any sort that might arise between you and FireLab.</p>
        <br></br>

        {/* Disputes */}
        <p><b>Disputes</b></p>
        <p>ANY DISPUTE RELATING IN ANY WAY TO YOUR USE OF FIRELAB’S WEBSITE OR SERVICES SHALL BE SUBMITTED TO CONFIDENTIAL BINDING ARBITRATION IN NEW YORK COUNTY, NEW YORK, NEW YORK EXCEPT FOR INTELLECTUAL PROPERTY CLAIMS BROUGHT BY EITHER PARTY (WHICH FOR PURPOSES OF THIS SECTION DO NOT INCLUDE PRIVACY AND PUBLICITY CLAIMS) AND CLAIMS THAT MAY BE BROUGHT IN SMALL-CLAIMS COURT.</p>
        <p>CONFIDENTIAL ARBITRATION UNDER THIS AGREEMENT SHALL BE RESOLVED EXCLUSIVELY UNDER THE COMMERCIAL ARBITRATION RULES THEN PREVAILING OF THE AMERICAN ARBITRATION ASSOCIATION ("AAA'S CONSUMER RULES"), EXCLUDING ANY RULES AND PROCEDURES GOVERNING OR PERMITTING CLASS OR REPRESENTATIVE ACTIONS. THE RULES ARE AVAILABLE AT THE AMERICAN ARBITRATION ASSOCIATION'S WEBSITE.</p>
        <p>YOU AND FIRELAB AGREE TO EXPRESSLY WAIVE ANY RIGHTS TO FILE CLASS OR REPRESENTATIVE ACTIONS OR SEEK RELIEF ON A CLASS OR REPRESENTATIVE BASIS IN ANY JURISDICTION OR FORUM.</p>
        <p>THE ARBITRATOR SHALL APPLY DELAWARE LAW, AND THE ARBITRATOR'S AWARD SHALL BE BINDING AND MAY BE ENTERED AS A JUDGMENT IN ANY COURT OF COMPETENT JURISDICTION. THERE SHALL BE NO APPEAL FROM ANY AWARD OF THE ARBITRATOR. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NO ARBITRATION UNDER THIS AGREEMENT SHALL BE JOINED TO AN ARBITRATION INVOLVING ANY OTHER PARTY SUBJECT TO THIS AGREEMENT, WHETHER THROUGH CLASS ARBITRATION PROCEEDINGS OR OTHERWISE. IF ANY PART OF THIS ARBITRATION PROVISION IS FOUND TO BE INVALID, UNENFORCEABLE OR ILLEGAL, THE REST OF THIS PROVISION SHALL REMAIN IN EFFECT.</p>
        <p>IF THE ENTIRE ARBITRATION PROVISION IS FOUND TO BE INVALID OR UNENFORCEABLE, THEN THE PARTIES CONSENT TO PERSONAL JURISDICTION AND EXCLUSIVE VENUE IN THE STATE COURT LOCATED IN NEW YORK COUNTY, NEW YORK, NEW YORK.</p>
        <p>FireLab's performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of FireLab's right to comply with governmental, court and law enforcement requests or requirements relating to your use of this Website or information provided to or gathered by FireLab with respect to such use.</p>
        <p>You may not assign or transfer any of your rights or obligations under these Terms of Use, in whole or in part, without our prior written consent, and any attempted assignment in violation of the foregoing will be null and void and of no force or effect. We may assign any and all of our rights and obligations under these Terms of Use freely at any time without notice. Subject to the foregoing, these Terms of Use will bind and inure to the benefit of your and our successors and permitted assigns.</p>
        <p>Our failure to exercise or enforce any right or provision shall not affect our right to exercise or enforce such right or provision at any time thereafter, nor shall our waiver of any breach or default of these Terms of Use constitute a waiver of any subsequent breach or default or a waiver of the provision itself.</p>
        <p>Whereas the Website has a feature that enables translation of these Terms of Use into a language other than English, the Terms of Use will be governed by the English language version.</p>
        <p>If any part of these Terms of Use is determined to be invalid or unenforceable pursuant to applicable law, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms of Use shall continue in effect.</p>
        <p>These Terms of Use constitute the entire agreement between you and FireLab with respect to this Website, except as otherwise indicated in these Terms of Use.</p>
        <br></br>

        {/* CONTACT INFORMATION */}
        <p><b>CONTACT INFORMATION</b></p>
        <p>You may contact FireLab regarding this Website at the following email address: hello@firelabinc.com. FireLab has designated the following email address to receive notifications of claimed copyright infringement involving this Website at hello@firelabinc.com. Please include in your notice a description of the copyrighted work, a description of where the material you claim is infringing is located on the Website, a statement that you are the copyright owner or its agent, and your address, telephone number, and email address.</p>
        <br></br>

        {/* RIGHTS TO SYNDICATE IMAGES, CONTENT, AND LISTINGS: */}
        <p><b>RIGHTS TO SYNDICATE IMAGES, CONTENT, AND LISTINGS:</b></p>
        <p>You hereby grant to FireLab, its subsidiaries, affiliates, and related companies, a perpetual and irrevocable license to copy, modify, display, distribute, create derivative works from, or otherwise use, any and all content that are displayed or submitted to this Website.</p>
        <br></br>

        {/* MISCELLANEOUS: */}
        <p><b>MISCELLANEOUS:</b></p>
        <p>Nothing contained in this agreement shall be deemed or interpreted to constitute the relationship between you and us as a legal partnership, agency, joint venture or any other relationship in which either you or we are responsible for or shall incur liability to outside parties as a result of the actions or omissions of the other. This agreement shall not be for the benefit of, or enforceable by, any person or entity not a party hereto and shall not confer any rights or remedies upon any party other than you and us and our respective successors and permitted assigns.</p>
        <p>Severability: In the event that any portion of this agreement is found to be unenforceable by a court of competent jurisdiction, the remaining portions shall remain in full force and effect to the degree necessary to preserve the intent of the parties.</p>
        <br></br>

        {/* NOTICES: */}
        <p><b>NOTICES:</b></p>
        <p>Any notice required or permitted to be given under this agreement shall be in writing and shall be deemed to have been duly given: when received if personally delivered; when transmitted if transmitted by electronic mail (Email) and a receipt is obtained; the day after it is sent if delivered by overnight delivery service and a receipt is obtained; and five days after it is sent if mailed, first class certified mail, return receipt requested, proper postage prepaid. In each case notices shall be sent to the last known address of the other party.</p>
        <p>LAST MODIFIED March 1, 2021 </p>
        <p>1 Data Protection</p>
        <p>1.1 Defined Terms: In this section 1, the terms “Controller”, “Data Subject”, “Personal Data Breach”, “Process” and “Processor” have the meanings given to them by the Data Protection Laws.</p>
        <p>1.2 Application of Data Protection Laws: Where the Data Protection Laws apply to the delivery of the Services under these Terms, the parties agree that FireLab shall act as a Processor, and that Customer shall either be (i) a Controller; or (ii) another Processor, subject to a separate agreement with the Controller of the Customer Personal Data.</p>
        <p>1.3 Obligations of FireLab: FireLab shall:</p>
        <p>1.3.1 Process Customer Personal Data, as described in Annex 1 to these Terms, solely on the documented instructions of Customer, for the purposes of providing the Services and as otherwise necessary to perform its obligations under these Terms including with regard to transfers of Customer Personal Data to a third country outside the European Union or an international organization (unless required by Union or Member State law to which FireLab is subject, in which case FireLab shall inform Customer of that legal requirement before such Processing, unless that law prohibits such information on important grounds of public interest); </p>
        <p>1.3.2 Ensure that persons authorized to process Customer Personal Data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality; </p>
        <p>1.3.3 Implement technical and organizational measures designed to ensure an appropriate level of security for Customer Personal Data, in accordance with Article 32 of the GDPR; </p>
        <p>1.3.4 Be generally authorized to engage another Processor to Process the Customer Personal Data (“Sub-Processor“), subject to FireLab: </p>
        <p>1.3.4.1 Notifying Customer of any intended changes to its use of Sub-Processors by posting notice of the intended change on FireLab's Sub-Processor Page. </p>
        <p>1.3.4.2 Including terms in its contract with each Sub-Processor which are no less protective than those set out in these Terms; and </p>
        <p>1.3.4.3 Remaining liable to the Customer for any failure by each Sub-Processor to fulfil its obligations in relation to the Processing of the Customer Personal Data. </p>
        <p>In relation to any notice received under section 1.3, the Customer shall have a period of 30 (thirty) days from the date of the notice to register any reasonable objection to the use of that Sub-Processor on the grounds of data protection. The parties will then, for a period of no more than 30 (thirty) days from the date of the Customer’s objection, work together in good faith to attempt to find a commercially reasonable solution for the Customer which avoids the use of the objected-to Sub-Processor. Where no such solution can be found, either party may (notwithstanding anything to the contrary in these Terms) erminate the relevant Services immediately on written notice to the other party; </p>
        <p>1.3.5 Notify Customer without undue delay of any communication from a Data Subject regarding the Processing of Customer Personal Data, or any other communication (including from a supervisory authority) relating to any obligation under the Data Protection Laws in respect of the Customer Personal Data and, taking into account the nature of the Processing, assist Customer by appropriate technical and organizational measures, insofar as this is possible, for the fulfillment of Customer’s obligation to respond to requests for exercising the data subject’s rights. In respect of such assistance, Customer agrees to pay FireLab for time exceeding one person hour] and for out of pocket expenses incurred by FireLab in connection with the performance of its obligations under this section 1.3.5; </p>
        <p>1.3.6 Notify Customer without undue delay upon becoming aware of any Personal Data Breach involving Customer Personal Data, and provide Customer with such information as is reasonably required by Customer to assist with its obligations to notify the Personal Data Breach under the Data Protection Laws, to the extent that this information is available to FireLab (and acknowledging that FireLab shall be entitled to provide this information in phases, as its investigation develops). Where it can be reasonably demonstrated that Customer (or any third party connected to Customer) was responsible for the Personal Data Breach (evidence of which shall include, but not be limited to, any related enforcement action taken against Customer or any connected third party by any supervisory authority), Customer shall reimburse FireLab's reasonable expenses in relation to its investigation and remediation of the Personal Data Breach; </p>
        <p>1.3.7 Provide reasonable assistance to Customer, upon request, in relation to any data protection impact assessments, or related consultations with supervisory authorities, which Customer is required to undertake pursuant to Articles 35 to 36 of the GDPR; </p>
        <p>1.3.8 To the extent that Customer is not able to self-serve its control or deletion of Customer Personal Data, provide reasonable assistance therewith to uphold the Customer’s right to have the Customer Personal Data returned or deleted following termination or expiry of these Terms; </p>
        <p>1.3.9 Make available to Customer on request all information necessary to demonstrate compliance with this section 1, and provide, on request, and, subject to clause 1.3.10, in full satisfaction of Customer’s right of audit and inspection (which Customer hereby expressly acknowledges), an independent audit report of FireLab's security measures in respect of its processing of Customer Personal Data; and </p>
        <p>1.3.10 Notwithstanding section 1.3.10, permit Customer, following a Personal Data Breach, and on at least 5 days’ prior notice, to inspect and audit the facilities used by FireLab for the processing of Customer Personal Data, subject to Customer bearing FireLab's reasonable costs. </p>
        <p>1.3.11 International Transfers: Customer expressly acknowledges that FireLab's processing facilities are located in the United States of America. To ensure compliance under the Data Protection Laws, Customer (as “data exporter”) and FireLab (as “data importer”), with effect from the commencement of the relevant transfer, hereby enter into the Standard Contractual Clauses in respect of any transfer from Customer to FireLab (or onward transfer) where such transfer would otherwise be prohibited by Data Protection Laws (or by the terms of data transfer agreements put in place to address Data Protection Laws). Appendix 1 to the Standard Contractual Clauses shall be deemed to be pre-populated with the relevant sections of Annex 1 to these Terms and the processing operations are deemed to be those described in these Terms. Appendix 2 to the Standard Contractual Clauses shall be deemed to be prepopulated with the following “Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood for the rights and freedoms of natural persons, FireLab shall implement appropriate technical and organizational measures as set forth in these Terms. </p>
        <p>1.3.12 Obligations of Customer: Customer acknowledges and confirms that: (i) all Customer Personal Data shall comply with and have been collected or otherwise obtained in compliance with Data Protection Laws, including by ensuring that there is a lawful basis for each Processing activity which Customer instructs FireLab to perform in relation to Customer Personal Data; (ii) Customer will take appropriate measures to ensure that the information referred to in Data Protection Laws, including Articles 13 and 14 of the GDPR, is made available to relevant Data Subjects in relation to the Processing by FireLab, for the purposes of which Customer may choose to reference the Application Privacy Notice made available by FireLab; and (iii) all instructions given by Customer to FireLab in respect of Customer Personal Data shall be in accordance with Data Protection Laws. </p>
        <p>1.3.13 Where the CCPA applies, if FireLab receives any Personal Information (as such term is defined by the CCPA) from or on behalf of Customer, then: </p>
        <p>1.3.14 FireLab will only process such Personal Information for the purpose of FireLab providing the Services; </p>
        <p>1.3.15 FireLab will not retain, use, or disclose such Personal Information: (i) for any purpose other than to perform the Services or (ii) outside of the direct business relationship between Customer and FireLab; </p>
        <p>1.3.16 FireLab will not sell, rent, release, disclose, disseminate, make available, transfer, or otherwise communicate such Personal Information to any third party for monetary or other valuable consideration; and </p>
        <p>1.3.17 FireLab certifies that it understands the restrictions on FireLab's processing such Personal Information as set forth in this section. FireLab may disclose Personal Information to FireLab's service providers in connection with such service providers providing services to FireLab; and FireLab may permit such service providers to process Personal Information as necessary for FireLab to provide the Services to Customer. </p>
        <p>1.3.18 Use of Aggregated Data: Customer acknowledges that FireLab collects and uses data from across its customer base in order to improve its products and services for its customers, and to carry out related research. FireLab takes steps to aggregate or otherwise de-identify any Customer data used for these purposes, and therefore does not knowingly process any personal data. However, to the extent that any such data is held to be personal data (or the equivalent term) in a particular jurisdiction, FireLab shall be the Controller (or the equivalent term) for the purposes of the applicable laws.</p>
        <br></br>
        <p>Miscellaneous:</p>
        <p>2.1 Amendment: FireLab may amend this Agreement from time to time, in which case the new Agreement will supersede prior versions. FireLab will notify Customer of any such amendments and Customer’s continued use of the FireLab Services following the effective date of any such amendment may be relied upon by FireLab as Customer’s consent to any such amendment. FireLab's failure to enforce at any time any provision of this Agreement does not constitute a waiver of that provision or of any other provision of the Agreement.</p>
        <p>2.2 Enforceability: If any provision of this Agreement shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severed from this Agreement and shall not affect the validity and enforceability of any remaining provisions. </p>
        <p>2.3 Modification: Except when expressly provided by another written agreement with FireLab, this is the entire Agreement between the parties relating to the subject matter herein and shall not be modified except in writing signed by an authorized representative of FireLab. Customer agrees that FireLab may, in its sole discretion, from time to time add to, delete from, or modify this Agreement in any reasonable manner by providing notice as permitted above. </p>
        <p>2.4 Force Majeure: FireLab shall not be deemed in breach of this Agreement, nor for any breach of any implied warranty or other obligation, for any failure in performance arising in connection with circumstances beyond its reasonable control, including, without limitation, fire, flood, storm, strike, lockout or other labor trouble, riot, war, rebellion, accident, or other acts of God. </p>
        <p>2.5 Transferability: The right to use the Service and access the Account is not transferable, sublicenseable, and may not be sold, rented, or timeshared, unless expressly permitted in another agreement with FireLab. FireLab may assign this Agreement, in whole or in part, at any time with or without notice. </p>
        <p>2.6 No Waiver: The failure of either party to require performance by the other party of any provision hereof shall not affect the full right to require such performance at any time thereafter; nor shall the waiver by either party of a breach of any provision hereof be taken or held to be a waiver of the provision itself. </p>
        <p>2.7 Relationship: Each party is an independent contractor in the performance of each and every part of this Agreement. Each party will be solely responsible for all of its employees and agents and its labor costs and expenses arising in connection therewith and for any and all claims, liabilities or damages or debts of any type whatsoever that may arise on account of its activities, or those of its employees or agents, in the performance of this Agreement. Customer does not have the authority to commit FireLab in any way and will not attempt to do so or imply that it has the right to do so.</p>
      </SectionLayout>
    </MainLayout>
  );
}


export default TermsOfUsePage;